apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: argocdexample-helm
  name: argocdexample-app-helm
spec:
  project: argocdexample-project
  source:
    repoURL: https://github.com/jorge-romero/lab-argocd-examples.git
    targetRevision: dev
    path: app-helm
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
