apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocdexample-app-helm
  namespace: argocd
spec:
  project: argocdexample-project
  source:
    repoURL: https://github.com/jorge-romero/lab-argocd-examples.git
    targetRevision: dev
    path: app-helm
    helm:
      releaseName: argocdexample-app-helm
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
