apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-website-service
spec:
  type: ClusterIP
  selector:
    app: argocdexample
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
