apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  labels:
    app: {{ .Values.metadata.labels.app }}
  name: {{ .Values.metadata.name }}-website-ingress-route
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.url }}`)
      priority: 10
      services:
        - name: {{ .Values.metadata.name }}-website-service
          port: 80
