apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}-website-deployment
  labels:
    app: {{ .Values.metadata.labels.app }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.metadata.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labels.app }}
    spec:
      containers:
      - name: {{ .Values.metadata.labels.app }}-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{ .Values.metadata.name }}-website-cm-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: {{ .Values.metadata.name }}-website-cm-volume 
        configMap:
          name: {{ .Values.metadata.name }}-website-cm
